var i18nstrings =
{'de':
{
	'title': 'Titel',
	'subtitle': 'Untertitel',
	'channel': 'Kanal',
	'channels': 'Kanäle',
	'allChannels': 'Alle Kanäle',
	'search': 'Suchen',
	'priority': 'Priorität',
	'start': 'Start',
	'config': 'Konfig.',
	'duration': 'Dauer',
	'status': 'Status',
	'save': 'Speichern',
	'cancel': 'Abbrechen',
	'delete': 'Löschen',
	'description': 'Beschreibung',
	'genre': 'Genre',
	'record': 'Aufnehmen',
	'errorCreatingOrDeleteRecordingEntry': 'Fehler beim Erstellen/Löschen der Aufnahme',
	'recordingEntryNotFound': 'Aufnahme nicht gefunden',
	'errorCancellingEntry': 'Fehler beim Abbrechen der Aufnahme',
	'errorDeletingEntry': 'Fehler beim Löschen der Aufnahme',
	'reallyDeleteItem': 'Möchten Sie diesen Eintrag wirklich löschen?',
	'active': 'aktiv',
	'inactive': 'inaktiv',
	'enabled': 'Aktiviert',
	'yes': 'Ja',
	'no': 'Nein',
	'tags': 'Tags',
	'tag': 'Tag',
	'createdBy': 'Erstellt von',
	'comment': 'Kommentar',
	'loading': 'Lade...',
	'monday': 'Montag',
	'monday.short': 'Mo',
	'tuesday': 'Dienstag',
	'tuesday.short': 'Di',
	'wednesday': 'Mittwoch',
	'wednesday.short': 'Mi',
	'thursday': 'Donnerstag',
	'thursday.short': 'Do',
	'friday': 'Freitag',
	'friday.short': 'Fr',
	'saturday': 'Samstag',
	'saturday.short': 'Sa',
	'sunday': 'Sonntag',
	'sunday.short': 'So',
	'upcomingRecordings': 'Kommende Aufnahmen',
	'finishedRecordings': 'Beendete Aufnahmen',
	'failedRecordings': 'Fehlerhafte Aufnahmen',
	'digitalVideoRecorder': 'Digitaler Videorekorder',
	'automaticRecorder': 'Auto-Aufnahme',
	'informationStatus': 'Informationen/Status',
	'electronicProgramGuide': 'Elektronischer Programmführer',
	'about': 'Über',
	'startingAround': 'Start (ca.)',
	'dateFormat': 'dd.MM.yyyy',
	'getMore': 'mehr...',
	'prio.important': 'Wichtig',
	'prio.high': 'Hoch',
	'prio.normal': 'Normal',
	'prio.low': 'Niedrig',
	'prio.unimportant': 'Unwichtig',
	'newEntry': 'Neuer Eintrag...',
	'subscriptions': 'Verbindungen',
	'adapters': 'Adapter',
	'any': '(egal)',
	'hostname': 'Hostname',
	'name': 'Name',
	'path': 'Pfad',
	'devicename': 'Gerätename',
	'deliverysystem':'System',
	'services':'Services',
	'muxes':'Muxes',
	'signal':'Signal',
	'reload':'Neu laden',
	'desktopSite':'Desktop-Version'
},
'en':
{
	'title': 'Title',
	'subtitle': 'Subtitle',
	'channel': 'Channel',
	'channels': 'Channels',
	'allChannels': 'All channels',
	'search': 'Search',
	'priority': 'Priority',
	'start': 'Start',
	'config': 'Config.',
	'duration': 'Duration',
	'status': 'Status',
	'save': 'Save',
	'cancel': 'Cancel',
	'delete': 'Delete',
	'description': 'Description',
	'genre': 'Genre',
	'record': 'Record',
	'errorCreatingOrDeleteRecordingEntry': 'Error creating or delete recording entry',
	'recordingEntryNotFound': 'Recording entry not found',
	'errorCancellingEntry': 'Error cancelling entry',
	'errorDeletingEntry': 'Error deleting entry',
	'reallyDeleteItem': 'Do you really want to delete this item?',
	'active': 'active',
	'inactive': 'inactive',
	'enabled': 'Enabled',
	'yes': 'Yes',
	'no': 'No',
	'tags': 'Tags',
	'tag': 'Tag',
	'createdBy': 'Created by',
	'comment': 'Comment',
	'loading': 'Loading...',
	'monday': 'Monday',
	'monday.short': 'Mon',
	'tuesday': 'Tuesday',
	'tuesday.short': 'Tue',
	'wednesday': 'Wednesday',
	'wednesday.short': 'Wed',
	'thursday': 'Thursday',
	'thursday.short': 'Thu',
	'friday': 'Friday',
	'friday.short': 'Fri',
	'saturday': 'Saturday',
	'saturday.short': 'Sat',
	'sunday': 'Sunday',
	'sunday.short': 'Sun',
	'upcomingRecordings': 'Upcoming recordings',
	'finishedRecordings': 'Finished recordings',
	'failedRecordings': 'Failed recordings',
	'digitalVideoRecorder': 'Digital video recorder',
	'automaticRecorder': 'Automatic recorder',
	'informationStatus': 'Information/Status',
	'electronicProgramGuide': 'Electronic program guide',
	'about': 'About',
	'startingAround': 'Start (ca.)',
	'dateFormat': 'yyyy-MM-dd',
	'getMore': 'more...',
	'prio.important': 'Important',
	'prio.high': 'High',
	'prio.normal': 'Normal',
	'prio.low': 'Low',
	'prio.unimportant': 'Unimportant',
	'newEntry': 'New entry...',
	'subscriptions': 'Subscriptions',
	'adapters': 'Adapters',
	'any': '(any)',
	'hostname': 'Hostname',
	'name': 'Name',
	'path': 'Path',
	'devicename': 'Device name',
	'deliverysystem':'System',
	'services':'Services',
	'muxes':'Muxes',
	'signal':'Signal',
	'reload':'Reload',
	'desktopSite':'Desktop-Site'
}
};